services:

  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php74-apache
    ports:
      - "80:80"
    volumes:
      - ./htdocs:/var/www/html
      - sessions_data:/var/www/html/cbt2.6admin/application/cache/sessions
      - client_sessions_data:/var/www/html/cbt2.6client/application/cache/sessions
    command: sh -c "mkdir -p /var/www/html/cbt2.6admin/application/cache/sessions /var/www/html/cbt2.6client/application/cache/sessions && chown -R www-data:www-data /var/www/html/cbt2.6admin/application/cache/sessions /var/www/html/cbt2.6client/application/cache/sessions && chmod 775 /var/www/html/cbt2.6admin/application/cache/sessions /var/www/html/cbt2.6client/application/cache/sessions && exec apache2-foreground"
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

  mariadb:
    image: mariadb:10.4
    container_name: mariadb104
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cbt25
      MYSQL_USER: cbt
      MYSQL_PASSWORD: smktkjTH46
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./htdocs/cbt2.6admin/Databases/cbt25.sql:/docker-entrypoint-initdb.d/01-cbt25.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u root -proot --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    restart: unless-stopped
    

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mariadb_data:
  sessions_data:
  client_sessions_data: