services:
  wordpress:
    image: wordpress:php8.5-apache
    container_name: wordpress85
    ports:
      - "8123:80"
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: project
      WORDPRESS_DB_USER: dukevii
      WORDPRESS_DB_PASSWORD: "Dika12345@"
    volumes:
      - wordpress_data:/var/www/html
      # - ./htdocs/wp-bkk/wp-content/themes/Mentor:/var/www/html/wp-content/themes/Mentor
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

  mariadb:
    image: mariadb:10.4
    container_name: mariadb104
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: dukevii
      MYSQL_PASSWORD: Dika12345@
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u root -proot --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mariadb_data:
  wordpress_data:
  sessions_data:
  client_sessions_data:
