date.timezone=Asia/Jakarta
display_errors=On
display_startup_errors=On
error_reporting=E_ALL

upload_max_filesize = 100000M
post_max_size = 48000M
memory_limit = 4096M
max_execution_time = 600000
max_input_vars = 5000000000000
max_input_time = 1000000